### ISSUE TITLE
core-layout element doesn't work, has to be div

### ISSUE THREAD

**Issue by robdodson** [googlearchive/core-layout#3]
Is there an example of a working `core-layout` element? The demo uses divs to do everything, which is odd but maybe I'm missing the point.

**Comment by sorvell** [comment]
It's a swiss army knife component that can be used in 3 primary ways:
- demo.html: shows using `core-layout.css`, a stylesheet that provides layout helper classes.
- demo-container.html: shows using `core-layout` element to layout its children
- demo-parent.html: shows using `core-layout` element to layout its parent's children

**Comment by sjmiles** [comment]
I think `core-layout` should default to `isContainer: true` if existing children are detected. I believe this is the basis of misunderstanding.

**Comment by sorvell** [comment]
It does.

**Comment by sjmiles** [comment]
Strange, yes, I see that in the code, but I remember recently being tripped up by needing `isContainer`. Looks like I drew a wrong conclusion, will have to track down the problem case.

**Comment by sorvell** [comment]
Element deprecated in favor of layout attributes.
